spring.application.name=library
spring.datasource.url=jdbc:postgresql://localhost:5432/iceb-library
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
security.jwt.secret-key=iceb-library-api
cors.allowed-origins=http://localhost:5173,http://localhost:8080,http://localhost:3000,https://localhost:5173,https://localhost:3000,http://147.182.128.51:8081,http://147.182.128.51:5173,https://147.182.128.51:5173,https://147.182.128.51:8080,http://bibliotecaiceb.ddns.net,http://bibliotecaiceb.ddns.net:5173,http://bibliotecaiceb.ddns.net:8080,https://bibliotecaiceb.ddns.net,https://bibliotecaiceb.ddns.net:5173,https://bibliotecaiceb.ddns.net:8080
cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
